name: Bug report
description: An unexpected problem or behavior.
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect instead? How to reproduce it?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Logs, environment, screenshots, or anything else relevant.
    validations:
      required: false
