name: Feature request
description: A request, idea, or new functionality.
type: Feature
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What problem does this solve? What's the proposed solution? Any alternatives considered?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, references, or anything else relevant.
    validations:
      required: false
